name: Auto-Fix
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  auto-fix:
    name: Auto-Fix
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.repo.full_name == github.repository
        name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - if: github.event.pull_request.head.repo.full_name != github.repository
        name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@2.17.0

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - run: vendor/bin/rector process --ansi

      - run: vendor/bin/ecs check --fix --ansi

      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: EndBug/add-and-commit@v8
        with:
          add: .
          message: "Rector Rectify"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
